import { assert, test } from '@codemod-utils/tests';

import { renameThis } from '../../../../src/utils/update-routes/index.js';

test('utils | update-routes | rename-this > base case', function () {
  const oldFile = [
    `{{page-title (t "routes.form.title")}}`,
    ``,
    `<Ui::Page @title={{t "routes.form.title"}}>`,
    `  <Ui::Form`,
    `    @data={{this.contactMe.initialData}}`,
    `    @instructions={{t "routes.form.contact-me-form.instructions"}}`,
    `    @onSubmit={{perform this.contactMe.submitData}}`,
    `    @title={{t "routes.form.contact-me-form.title"}}`,
    `    as |F|`,
    `  >`,
    `    <div class={{this.styles.field}}>`,
    `      <F.Input`,
    `        @isRequired={{true}}`,
    `        @key="name"`,
    `        @label={{t "routes.form.contact-me-form.fields.name.label"}}`,
    `        @placeholder={{t`,
    `          "routes.form.contact-me-form.fields.name.placeholder"`,
    `        }}`,
    `      />`,
    `    </div>`,
    ``,
    `    <div class={{this.styles.field}}>`,
    `      <F.Input`,
    `        @isRequired={{true}}`,
    `        @key="email"`,
    `        @label={{t "routes.form.contact-me-form.fields.email.label"}}`,
    `        @placeholder={{t`,
    `          "routes.form.contact-me-form.fields.email.placeholder"`,
    `        }}`,
    `        @type="email"`,
    `      />`,
    `    </div>`,
    ``,
    `    <div class={{this.styles.field}}>`,
    `      <F.Textarea`,
    `        @key="message"`,
    `        @label={{t "routes.form.contact-me-form.fields.message.label"}}`,
    `      />`,
    `    </div>`,
    ``,
    `    {{#if this.contactMe.showSubscribe}}`,
    `      <div class={{this.styles.field}}>`,
    `        <F.Checkbox`,
    `          @key="subscribe"`,
    `          @label={{t "routes.form.contact-me-form.fields.subscribe.label"}}`,
    `        />`,
    `      </div>`,
    `    {{else}}`,
    `      <div class={{this.styles.field}}>`,
    `        <F.Number`,
    `          @key="donation"`,
    `          @label={{t "routes.form.contact-me-form.fields.donation.label"}}`,
    `          @minValue={{0}}`,
    `          @placeholder={{t`,
    `            "routes.form.contact-me-form.fields.donation.placeholder"`,
    `          }}`,
    `          @step={{10}}`,
    `        />`,
    `      </div>`,
    `    {{/if}}`,
    `  </Ui::Form>`,
    `</Ui::Page>`,
  ].join('\n');

  const newFile = renameThis(oldFile);

  assert.strictEqual(
    newFile,
    [
      `{{page-title (t "routes.form.title")}}`,
      ``,
      `<Ui::Page @title={{t "routes.form.title"}}>`,
      `  <Ui::Form`,
      `    @data={{@controller.contactMe.initialData}}`,
      `    @instructions={{t "routes.form.contact-me-form.instructions"}}`,
      `    @onSubmit={{perform @controller.contactMe.submitData}}`,
      `    @title={{t "routes.form.contact-me-form.title"}}`,
      `    as |F|`,
      `  >`,
      `    <div class={{@controller.styles.field}}>`,
      `      <F.Input`,
      `        @isRequired={{true}}`,
      `        @key="name"`,
      `        @label={{t "routes.form.contact-me-form.fields.name.label"}}`,
      `        @placeholder={{t`,
      `          "routes.form.contact-me-form.fields.name.placeholder"`,
      `        }}`,
      `      />`,
      `    </div>`,
      ``,
      `    <div class={{@controller.styles.field}}>`,
      `      <F.Input`,
      `        @isRequired={{true}}`,
      `        @key="email"`,
      `        @label={{t "routes.form.contact-me-form.fields.email.label"}}`,
      `        @placeholder={{t`,
      `          "routes.form.contact-me-form.fields.email.placeholder"`,
      `        }}`,
      `        @type="email"`,
      `      />`,
      `    </div>`,
      ``,
      `    <div class={{@controller.styles.field}}>`,
      `      <F.Textarea`,
      `        @key="message"`,
      `        @label={{t "routes.form.contact-me-form.fields.message.label"}}`,
      `      />`,
      `    </div>`,
      ``,
      `    {{#if @controller.contactMe.showSubscribe}}`,
      `      <div class={{@controller.styles.field}}>`,
      `        <F.Checkbox`,
      `          @key="subscribe"`,
      `          @label={{t "routes.form.contact-me-form.fields.subscribe.label"}}`,
      `        />`,
      `      </div>`,
      `    {{else}}`,
      `      <div class={{@controller.styles.field}}>`,
      `        <F.Number`,
      `          @key="donation"`,
      `          @label={{t "routes.form.contact-me-form.fields.donation.label"}}`,
      `          @minValue={{0}}`,
      `          @placeholder={{t`,
      `            "routes.form.contact-me-form.fields.donation.placeholder"`,
      `          }}`,
      `          @step={{10}}`,
      `        />`,
      `      </div>`,
      `    {{/if}}`,
      `  </Ui::Form>`,
      `</Ui::Page>`,
    ].join('\n'),
  );
});
