import { assert, normalizeFile, test } from '@codemod-utils/tests';

import { insertTemplateTag } from '../../../../src/utils/update-tests/index.js';

test('utils | update-tests | insert-template-tag > edge case (hbs is outside of render)', function () {
  const oldFile = normalizeFile([
    `import { findAll, render } from '@ember/test-helpers';`,
    `import { a11yAudit } from 'ember-a11y-testing/test-support';`,
    `import { hbs } from 'ember-cli-htmlbars';`,
    `import { getClassForNavigationMenu as getClass } from 'my-addon/test-support';`,
    `import { setupRenderingTest } from 'my-app/tests/helpers';`,
    `import { module, test } from 'qunit';`,
    ``,
    `const template = hbs\``,
    `  <NavigationMenu @menuItems={{this.menuItems}} @name="Main Navigation" />`,
    `\`;`,
    ``,
    `module('Integration | Component | navigation-menu', function (hooks) {`,
    `  setupRenderingTest(hooks);`,
    ``,
    `  test('it renders', async function (assert) {`,
    `    this.menuItems = [`,
    `      {`,
    `        label: 'Home',`,
    `        route: 'index',`,
    `      },`,
    `    ];`,
    ``,
    `    await render(template);`,
    ``,
    `    assert`,
    `      .dom('[data-test-nav="Main Navigation"]')`,
    `      .hasAria('label', 'Main Navigation')`,
    `      .hasTagName('nav');`,
    ``,
    `    const links = findAll('[data-test-link]');`,
    ``,
    `    assert.strictEqual(links.length, 1);`,
    ``,
    `    assert.dom(links[0]).hasAttribute('href', '/').hasText('Home');`,
    ``,
    `    await a11yAudit();`,
    `  });`,
    ``,
    `  test('CSS modules', async function (assert) {`,
    `    this.menuItems = [`,
    `      {`,
    `        label: 'Home',`,
    `        route: 'index',`,
    `      },`,
    `    ];`,
    ``,
    `    await render(template);`,
    ``,
    `    assert.dom('[data-test-link="Home"]').hasClass(getClass('link'));`,
    `  });`,
    `});`,
    ``,
  ]);

  const newFile = insertTemplateTag(oldFile, {
    isTypeScript: true,
    useLexicalThis: true,
  });

  assert.strictEqual(
    newFile,
    normalizeFile([
      `import { findAll, render } from '@ember/test-helpers';`,
      `import { a11yAudit } from 'ember-a11y-testing/test-support';`,
      `import { hbs } from 'ember-cli-htmlbars';`,
      `import { getClassForNavigationMenu as getClass } from 'my-addon/test-support';`,
      `import { setupRenderingTest } from 'my-app/tests/helpers';`,
      `import { module, test } from 'qunit';`,
      ``,
      `const template = hbs\``,
      `  <NavigationMenu @menuItems={{this.menuItems}} @name="Main Navigation" />`,
      `\`;`,
      ``,
      `module('Integration | Component | navigation-menu', function (hooks) {`,
      `  setupRenderingTest(hooks);`,
      ``,
      `  test('it renders', async function (assert) {`,
      `    this.menuItems = [`,
      `      {`,
      `        label: 'Home',`,
      `        route: 'index',`,
      `      },`,
      `    ];`,
      ``,
      `    await render(template);`,
      ``,
      `    assert`,
      `      .dom('[data-test-nav="Main Navigation"]')`,
      `      .hasAria('label', 'Main Navigation')`,
      `      .hasTagName('nav');`,
      ``,
      `    const links = findAll('[data-test-link]');`,
      ``,
      `    assert.strictEqual(links.length, 1);`,
      ``,
      `    assert.dom(links[0]).hasAttribute('href', '/').hasText('Home');`,
      ``,
      `    await a11yAudit();`,
      `  });`,
      ``,
      `  test('CSS modules', async function (assert) {`,
      `    this.menuItems = [`,
      `      {`,
      `        label: 'Home',`,
      `        route: 'index',`,
      `      },`,
      `    ];`,
      ``,
      `    await render(template);`,
      ``,
      `    assert.dom('[data-test-link="Home"]').hasClass(getClass('link'));`,
      `  });`,
      `});`,
      ``,
    ]),
  );
});
