import { normalize } from 'node:path';

import { normalizeFile } from '@codemod-utils/tests';

import type {
  CodemodOptions,
  Options,
  Packages,
} from '../../../src/types/index.js';

const codemodOptions: CodemodOptions = {
  componentStructure: 'flat',
  convert: new Set(['components', 'routes', 'tests']),
  folder: '',
  projectRoot: 'tmp/my-v1-app',
};

const inputProject = {
  app: {
    components: {
      ui: {
        form: {
          'checkbox.hbs': ``,
          'checkbox.ts': normalizeFile([
            `import Component from '@glimmer/component';`,
            ``,
            `interface UiFormCheckboxSignature {}`,
            ``,
            `export default class UiFormCheckbox extends Component<UiFormCheckboxSignature> {}`,
            ``,
            `declare module '@glint/environment-ember-loose/registry' {`,
            `  export default interface Registry {`,
            `    'Ui::Form::Checkbox': typeof UiFormCheckbox;`,
            `    'ui/form/checkbox': typeof UiFormCheckbox;`,
            `  }`,
            `}`,
            ``,
          ]),
          'field.hbs': ``,
          'field.ts': normalizeFile([
            `import Component from '@glimmer/component';`,
            ``,
            `interface UiFormFieldSignature {}`,
            ``,
            `export default class UiFormField extends Component<UiFormFieldSignature> {}`,
            ``,
          ]),
          'information.hbs': ``,
          'information.ts': normalizeFile([
            `import templateOnlyComponent from '@ember/component/template-only';`,
            ``,
            `interface UiFormInformationSignature {}`,
            ``,
            `const UiFormInformation = templateOnlyComponent<UiFormInformationSignature>();`,
            ``,
            `export default UiFormInformation;`,
            ``,
            `declare module '@glint/environment-ember-loose/registry' {`,
            `  export default interface Registry {`,
            `    'Ui::Form::Information': typeof UiFormInformation;`,
            `    'ui/form/information': typeof UiFormInformation;`,
            `  }`,
            `}`,
            ``,
          ]),
          'input.hbs': ``,
          'input.js': normalizeFile([
            `import Component from '@glimmer/component';`,
            ``,
            `export default class UiFormInput extends Component {}`,
            ``,
          ]),
          'number.gts': ``,
          'select.hbs': ``,
          'select.ts': normalizeFile([
            `import Component from '@glimmer/component';`,
            ``,
            `interface UiFormSelectSignature {}`,
            ``,
            `export default class UiFormSelect extends Component<UiFormSelectSignature> {}`,
            ``,
          ]),
          'textarea.gjs': ``,
        },
        'form.hbs': ``,
        'form.ts': normalizeFile([
          `import Component from '@glimmer/component';`,
          ``,
          `interface UiFormSignature {}`,
          ``,
          `export default class UiForm extends Component<UiFormSignature> {}`,
          ``,
        ]),
        'page.hbs': ``,
        'page.js': normalizeFile([
          `import templateOnlyComponent from '@ember/component/template-only';`,
          ``,
          `const UiPage = templateOnlyComponent();`,
          ``,
          `export default UiPage;`,
          ``,
        ]),
      },
      'navigation-menu.hbs': '',
      'select-locale.hbs': '',
      'select-locale.js': normalizeFile([
        `import Component from '@glimmer/component';`,
        ``,
        `export default class SelectLocale extends Component {}`,
        ``,
      ]),
    },
    templates: {
      'application.hbs': normalizeFile([
        `<header>`,
        `  <NavigationMenu />`,
        `</header>`,
        ``,
        `<main>`,
        `  {{outlet}}`,
        `</main>`,
      ]),
      'index.hbs': `<SelectLocale />`,
    },
  },
  tests: {
    integration: {
      components: {
        ui: {
          form: {
            'checkbox-test.ts': normalizeFile([
              `import {`,
              `  render,`,
              `  type TestContext as BaseTestContext,`,
              `} from '@ember/test-helpers';`,
              `import { hbs } from 'ember-cli-htmlbars';`,
              `import { UiForm } from 'my-addon/test-support';`,
              `import { setupRenderingTest } from 'my-v1-app/tests/helpers';`,
              `import { module, test } from 'qunit';`,
              ``,
              `interface TestContext extends BaseTestContext {`,
              `  parent: UiForm;`,
              `}`,
              ``,
              `module('Integration | Component | ui/form/checkbox', function (hooks) {`,
              `  setupRenderingTest(hooks);`,
              ``,
              `  hooks.beforeEach(function (this: TestContext) {`,
              `    this.parent = new UiForm();`,
              `  });`,
              ``,
              `  test('it renders', async function (this: TestContext, assert) {`,
              `    await render<TestContext>(`,
              `      hbs\``,
              `        <Ui::Form::Checkbox`,
              `          @data={{this.parent.data}}`,
              `          @key="subscribe"`,
              `          @label="Subscribe to The Ember Times?"`,
              `          @onUpdate={{this.parent.updateData}}`,
              `        />`,
              `      \`,`,
              `    );`,
              ``,
              `    assert.ok(true);`,
              `  });`,
              `});`,
              ``,
            ]),
            'field-test.ts': '',
            'information-test.ts': '',
            'input-test.gjs': '',
            'number-test.gts': '',
            'select-test.gts': '',
            'textarea-test.js': normalizeFile([
              `import { render } from '@ember/test-helpers';`,
              `import { hbs } from 'ember-cli-htmlbars';`,
              `import { setupRenderingTest } from 'my-v1-app/tests/helpers';`,
              `import { module, test } from 'qunit';`,
              ``,
              `module('Integration | Component | ui/form/textarea', function (hooks) {`,
              `  setupRenderingTest(hooks);`,
              ``,
              `  hooks.beforeEach(function () {`,
              `    this.data = {`,
              `      email: 'zoey@emberjs.com',`,
              `      message: 'I 🧡 container queries!',`,
              `      name: 'Zoey',`,
              `      subscribe: false,`,
              `    };`,
              ``,
              `    this.updateData = () => {`,
              `      // Do nothing`,
              `    };`,
              `  });`,
              ``,
              `  test('it renders', async function (assert) {`,
              `    await render(`,
              `      hbs\``,
              `        <Ui::Form::Textarea`,
              `          @data={{this.data}}`,
              `          @key="message"`,
              `          @label="Message"`,
              `          @onUpdate={{this.updateData}}`,
              `        />`,
              `      \`,`,
              `    );`,
              ``,
              `    assert.ok(true);`,
              `  });`,
              `});`,
              ``,
            ]),
          },
          'form-test.ts': '',
          'page-test.gjs': '',
        },
        'navigation-menu-test.js': '',
        'select-locale-test.js': '',
      },
    },
  },
  'package.json': JSON.stringify({
    name: 'my-v1-app',
    version: '1.0.0',
    devDependencies: {
      '@embroider/webpack': '^4.1.1',
      'ember-source': '~6.7.0',
    },
  }),
};

const options: Options = {
  componentStructure: 'flat',
  convert: {
    components: true,
    routes: true,
    tests: true,
  },
  folder: '',
  projectRoot: 'tmp/my-v1-app',
};

const packages: Packages = new Map([
  [
    'my-v1-app',
    {
      filesWithHBS: {
        components: [
          'app/components/navigation-menu.hbs',
          'app/components/select-locale.hbs',
          'app/components/ui/form.hbs',
          'app/components/ui/form/checkbox.hbs',
          'app/components/ui/form/field.hbs',
          'app/components/ui/form/information.hbs',
          'app/components/ui/form/input.hbs',
          'app/components/ui/form/select.hbs',
          'app/components/ui/page.hbs',
        ].map(normalize),
        routes: [
          'app/templates/application.hbs',
          'app/templates/index.hbs',
        ].map(normalize),
        tests: [
          'tests/integration/components/navigation-menu-test.js',
          'tests/integration/components/select-locale-test.js',
          'tests/integration/components/ui/form-test.ts',
          'tests/integration/components/ui/form/checkbox-test.ts',
          'tests/integration/components/ui/form/field-test.ts',
          'tests/integration/components/ui/form/information-test.ts',
          'tests/integration/components/ui/form/textarea-test.js',
        ].map(normalize),
      },
      filesWithTemplateTag: {
        components: [],
        routes: [],
        tests: [],
      },
      hasEmberRouteTemplate: false,
      packageRoot: 'tmp/my-v1-app',
      packageType: 'v1-app',
    },
  ],
]);

export { codemodOptions, inputProject, options, packages };
