import {
  assertFixture,
  loadFixture,
  normalizeFile,
  test,
} from '@codemod-utils/tests';

import { findEntities, updateRoutes } from '../../../src/steps/index.js';
import {
  inputProject,
  options,
  packages,
} from '../../helpers/shared-test-setups/my-v2-app.js';

test('steps | update-routes > v2-app', function () {
  const outputProject = {
    app: {
      components: {
        ui: {
          form: {
            'checkbox.hbs': ``,
            'checkbox.ts': normalizeFile([
              `import Component from '@glimmer/component';`,
              ``,
              `interface UiFormCheckboxSignature {}`,
              ``,
              `export default class UiFormCheckbox extends Component<UiFormCheckboxSignature> {}`,
              ``,
              `declare module '@glint/environment-ember-loose/registry' {`,
              `  export default interface Registry {`,
              `    'Ui::Form::Checkbox': typeof UiFormCheckbox;`,
              `    'ui/form/checkbox': typeof UiFormCheckbox;`,
              `  }`,
              `}`,
              ``,
            ]),
            'field.hbs': ``,
            'field.ts': normalizeFile([
              `import Component from '@glimmer/component';`,
              ``,
              `interface UiFormFieldSignature {}`,
              ``,
              `export default class UiFormField extends Component<UiFormFieldSignature> {}`,
              ``,
            ]),
            'information.hbs': ``,
            'information.ts': normalizeFile([
              `import templateOnlyComponent from '@ember/component/template-only';`,
              ``,
              `interface UiFormInformationSignature {}`,
              ``,
              `const UiFormInformation = templateOnlyComponent<UiFormInformationSignature>();`,
              ``,
              `export default UiFormInformation;`,
              ``,
              `declare module '@glint/environment-ember-loose/registry' {`,
              `  export default interface Registry {`,
              `    'Ui::Form::Information': typeof UiFormInformation;`,
              `    'ui/form/information': typeof UiFormInformation;`,
              `  }`,
              `}`,
              ``,
            ]),
            'input.hbs': ``,
            'input.js': normalizeFile([
              `import Component from '@glimmer/component';`,
              ``,
              `export default class UiFormInput extends Component {}`,
              ``,
            ]),
            'number.gts': ``,
            'select.hbs': ``,
            'select.ts': normalizeFile([
              `import Component from '@glimmer/component';`,
              ``,
              `interface UiFormSelectSignature {}`,
              ``,
              `export default class UiFormSelect extends Component<UiFormSelectSignature> {}`,
              ``,
            ]),
            'textarea.gjs': ``,
          },
          'form.hbs': ``,
          'form.ts': normalizeFile([
            `import Component from '@glimmer/component';`,
            ``,
            `interface UiFormSignature {}`,
            ``,
            `export default class UiForm extends Component<UiFormSignature> {}`,
            ``,
          ]),
          'page.hbs': ``,
          'page.js': normalizeFile([
            `import templateOnlyComponent from '@ember/component/template-only';`,
            ``,
            `const UiPage = templateOnlyComponent();`,
            ``,
            `export default UiPage;`,
            ``,
          ]),
        },
        'navigation-menu.hbs': '',
        'select-locale.hbs': '',
        'select-locale.js': normalizeFile([
          `import Component from '@glimmer/component';`,
          ``,
          `export default class SelectLocale extends Component {}`,
          ``,
        ]),
      },
      templates: {
        'application.gjs': normalizeFile([
          `import NavigationMenu from 'my-v2-app/components/navigation-menu';`,
          ``,
          `<template>`,
          `<header>`,
          `  <NavigationMenu />`,
          `</header>`,
          ``,
          `<main>`,
          `  {{outlet}}`,
          `</main>`,
          `</template>`,
          ``,
        ]),
        'index.gjs': normalizeFile([
          `import SelectLocale from 'my-v2-app/components/select-locale';`,
          ``,
          `<template>`,
          `<SelectLocale />`,
          `</template>`,
          ``,
        ]),
      },
    },
    tests: {
      integration: {
        components: {
          ui: {
            form: {
              'checkbox-test.ts': normalizeFile([
                `import {`,
                `  render,`,
                `  type TestContext as BaseTestContext,`,
                `} from '@ember/test-helpers';`,
                `import { hbs } from 'ember-cli-htmlbars';`,
                `import { UiForm } from 'my-addon/test-support';`,
                `import { setupRenderingTest } from 'my-v2-app/tests/helpers';`,
                `import { module, test } from 'qunit';`,
                ``,
                `interface TestContext extends BaseTestContext {`,
                `  parent: UiForm;`,
                `}`,
                ``,
                `module('Integration | Component | ui/form/checkbox', function (hooks) {`,
                `  setupRenderingTest(hooks);`,
                ``,
                `  hooks.beforeEach(function (this: TestContext) {`,
                `    this.parent = new UiForm();`,
                `  });`,
                ``,
                `  test('it renders', async function (this: TestContext, assert) {`,
                `    await render<TestContext>(`,
                `      hbs\``,
                `        <Ui::Form::Checkbox`,
                `          @data={{this.parent.data}}`,
                `          @key="subscribe"`,
                `          @label="Subscribe to The Ember Times?"`,
                `          @onUpdate={{this.parent.updateData}}`,
                `        />`,
                `      \`,`,
                `    );`,
                ``,
                `    assert.ok(true);`,
                `  });`,
                `});`,
                ``,
              ]),
              'field-test.ts': '',
              'information-test.ts': '',
              'input-test.gjs': '',
              'number-test.gts': '',
              'select-test.gts': '',
              'textarea-test.js': normalizeFile([
                `import { render } from '@ember/test-helpers';`,
                `import { hbs } from 'ember-cli-htmlbars';`,
                `import { setupRenderingTest } from 'my-v2-app/tests/helpers';`,
                `import { module, test } from 'qunit';`,
                ``,
                `module('Integration | Component | ui/form/textarea', function (hooks) {`,
                `  setupRenderingTest(hooks);`,
                ``,
                `  hooks.beforeEach(function () {`,
                `    this.data = {`,
                `      email: 'zoey@emberjs.com',`,
                `      message: 'I 🧡 container queries!',`,
                `      name: 'Zoey',`,
                `      subscribe: false,`,
                `    };`,
                ``,
                `    this.updateData = () => {`,
                `      // Do nothing`,
                `    };`,
                `  });`,
                ``,
                `  test('it renders', async function (assert) {`,
                `    await render(`,
                `      hbs\``,
                `        <Ui::Form::Textarea`,
                `          @data={{this.data}}`,
                `          @key="message"`,
                `          @label="Message"`,
                `          @onUpdate={{this.updateData}}`,
                `        />`,
                `      \`,`,
                `    );`,
                ``,
                `    assert.ok(true);`,
                `  });`,
                `});`,
                ``,
              ]),
            },
            'form-test.ts': '',
            'page-test.gjs': '',
          },
          'navigation-menu-test.js': '',
          'select-locale-test.js': '',
        },
      },
    },
    'package.json': JSON.stringify({
      name: 'my-v2-app',
      version: '1.0.0',
      devDependencies: {
        '@embroider/vite': '^1.2.0',
        'ember-source': '~6.7.0',
      },
    }),
  };

  loadFixture(inputProject, options);

  const entities = findEntities(options);

  updateRoutes(packages, entities);

  assertFixture(outputProject, options);
});
