import {
  assertFixture,
  createFile,
  loadFixture,
  test,
} from '@codemod-utils/tests';

import { findEntities, updateComponents } from '../../../src/steps/index.js';
import {
  inputProject,
  options,
  packages,
} from '../../helpers/shared-test-setups/my-v1-app.js';

test('steps | update-components > v1-app', function () {
  const outputProject = {
    app: {
      components: {
        ui: {
          form: {
            'checkbox.gts': createFile([
              `import Component from '@glimmer/component';`,
              ``,
              `interface UiFormCheckboxSignature {}`,
              ``,
              `export default class UiFormCheckbox extends Component<UiFormCheckboxSignature> {`,
              `  <template>`,
              ``,
              `  </template>`,
              `}`,
              ``,
              `declare module '@glint/environment-ember-loose/registry' {`,
              `  export default interface Registry {`,
              `    'Ui::Form::Checkbox': typeof UiFormCheckbox;`,
              `    'ui/form/checkbox': typeof UiFormCheckbox;`,
              `  }`,
              `}`,
              ``,
            ]),
            'field.gts': createFile([
              `import Component from '@glimmer/component';`,
              ``,
              `interface UiFormFieldSignature {}`,
              ``,
              `export default class UiFormField extends Component<UiFormFieldSignature> {`,
              `    <template>`,
              ``,
              `    </template>`,
              `}`,
              ``,
            ]),
            'information.gts': createFile([
              `import type { TOC } from '@ember/component/template-only';`,
              ``,
              `interface UiFormInformationSignature {}`,
              ``,
              `const UiFormInformation = <template>`,
              ``,
              `</template> satisfies TOC<UiFormInformationSignature>;`,
              ``,
              `export default UiFormInformation;`,
              ``,
              `declare module '@glint/environment-ember-loose/registry' {`,
              `  export default interface Registry {`,
              `    'Ui::Form::Information': typeof UiFormInformation;`,
              `    'ui/form/information': typeof UiFormInformation;`,
              `  }`,
              `}`,
              ``,
            ]),
            'input.gjs': createFile([
              `import Component from '@glimmer/component';`,
              ``,
              `export default class UiFormInput extends Component {`,
              `    <template>`,
              ``,
              `    </template>`,
              `}`,
              ``,
            ]),
            'number.gts': ``,
            'select.gts': createFile([
              `import Component from '@glimmer/component';`,
              ``,
              `interface UiFormSelectSignature {}`,
              ``,
              `export default class UiFormSelect extends Component<UiFormSelectSignature> {`,
              `    <template>`,
              ``,
              `    </template>`,
              `}`,
              ``,
            ]),
            'textarea.gjs': ``,
          },
          'form.gts': createFile([
            `import Component from '@glimmer/component';`,
            ``,
            `interface UiFormSignature {}`,
            ``,
            `export default class UiForm extends Component<UiFormSignature> {`,
            `    <template>`,
            ``,
            `    </template>`,
            `}`,
            ``,
          ]),
          'page.gjs': createFile([
            `const UiPage = <template>`,
            ``,
            `</template>;`,
            ``,
            `export default UiPage;`,
            ``,
          ]),
        },
        'navigation-menu.gjs': createFile([
          `<template>`,
          ``,
          `</template>`,
          ``,
        ]),
        'select-locale.gjs': createFile([
          `import Component from '@glimmer/component';`,
          ``,
          `export default class SelectLocale extends Component {`,
          `    <template>`,
          ``,
          `    </template>`,
          `}`,
          ``,
        ]),
      },
      templates: {
        'application.hbs': createFile([
          `<header>`,
          `  <NavigationMenu />`,
          `</header>`,
          ``,
          `<main>`,
          `  {{outlet}}`,
          `</main>`,
        ]),
        'index.hbs': `<SelectLocale />`,
      },
    },
    tests: {
      integration: {
        components: {
          ui: {
            form: {
              'checkbox-test.ts': createFile([
                `import {`,
                `  render,`,
                `  type TestContext as BaseTestContext,`,
                `} from '@ember/test-helpers';`,
                `import { hbs } from 'ember-cli-htmlbars';`,
                `import { UiForm } from 'my-addon/test-support';`,
                `import { setupRenderingTest } from 'my-v1-app/tests/helpers';`,
                `import { module, test } from 'qunit';`,
                ``,
                `interface TestContext extends BaseTestContext {`,
                `  parent: UiForm;`,
                `}`,
                ``,
                `module('Integration | Component | ui/form/checkbox', function (hooks) {`,
                `  setupRenderingTest(hooks);`,
                ``,
                `  hooks.beforeEach(function (this: TestContext) {`,
                `    this.parent = new UiForm();`,
                `  });`,
                ``,
                `  test('it renders', async function (this: TestContext, assert) {`,
                `    await render<TestContext>(`,
                `      hbs\``,
                `        <Ui::Form::Checkbox`,
                `          @data={{this.parent.data}}`,
                `          @key="subscribe"`,
                `          @label="Subscribe to The Ember Times?"`,
                `          @onUpdate={{this.parent.updateData}}`,
                `        />`,
                `      \`,`,
                `    );`,
                ``,
                `    assert.ok(true);`,
                `  });`,
                `});`,
                ``,
              ]),
              'field-test.ts': '',
              'information-test.ts': '',
              'input-test.gjs': '',
              'number-test.gts': '',
              'select-test.gts': '',
              'textarea-test.js': createFile([
                `import { render } from '@ember/test-helpers';`,
                `import { hbs } from 'ember-cli-htmlbars';`,
                `import { setupRenderingTest } from 'my-v1-app/tests/helpers';`,
                `import { module, test } from 'qunit';`,
                ``,
                `module('Integration | Component | ui/form/textarea', function (hooks) {`,
                `  setupRenderingTest(hooks);`,
                ``,
                `  hooks.beforeEach(function () {`,
                `    this.data = {`,
                `      email: 'zoey@emberjs.com',`,
                `      message: 'I 🧡 container queries!',`,
                `      name: 'Zoey',`,
                `      subscribe: false,`,
                `    };`,
                ``,
                `    this.updateData = () => {`,
                `      // Do nothing`,
                `    };`,
                `  });`,
                ``,
                `  test('it renders', async function (assert) {`,
                `    await render(`,
                `      hbs\``,
                `        <Ui::Form::Textarea`,
                `          @data={{this.data}}`,
                `          @key="message"`,
                `          @label="Message"`,
                `          @onUpdate={{this.updateData}}`,
                `        />`,
                `      \`,`,
                `    );`,
                ``,
                `    assert.ok(true);`,
                `  });`,
                `});`,
                ``,
              ]),
            },
            'form-test.ts': '',
            'page-test.gjs': '',
          },
          'navigation-menu-test.js': '',
          'select-locale-test.js': '',
        },
      },
    },
    'package.json': JSON.stringify({
      name: 'my-v1-app',
      version: '1.0.0',
      devDependencies: {
        '@embroider/webpack': '^4.1.1',
        'ember-source': '~6.7.0',
      },
    }),
  };

  loadFixture(inputProject, options);

  const entities = findEntities(options);

  updateComponents(packages, entities);

  assertFixture(outputProject, options);
});
